version: '3.8'

networks:
  my_network:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: ManagementGraduationProject
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_1:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - my_network

  webapi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aspnet6_container
    ports:
      - "5000:7274"
      - "8080:80"
      - "5001:5000"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DB: "Server=mysql;Port=3306;Database=ManagementGraduationProject;Uid=root;Pwd=123456;"
    networks:
      - my_network
volumes:
  mysql_data_1:
