version: '3.8'

networks:
  my_network:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "YourStrong!Passw0rd"
      MYSQL_DATABASE: "ductmweb_ManagementGraduationProject"
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
    ports:
      - "3307:3306"
    volumes:
      - ./my_database.sql:/docker-entrypoint-initdb.d/my_database.sql
    restart: always
    networks:
      - my_network

  webapi:
    build: .
    container_name: aspnet6_container
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=ductmweb_ManagementGraduationProject;User=myuser;Password=mypassword;"
    networks:
      - my_network
